# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMES():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mES(self):
    self.driver.get("http://localhost:52760/pages/login.html")
    self.driver.set_window_size(841, 724)
    self.driver.find_element(By.ID, "userName").send_keys("cs")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.ID, "userName").send_keys("卢鹏")
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
    self.driver.find_element(By.ID, "DengLu").click()
    self.driver.find_element(By.LINK_TEXT, "生产日报").click()
    self.driver.find_element(By.LINK_TEXT, "标准合焊").click()
    self.driver.find_element(By.LINK_TEXT, "点焊").click()
    self.driver.find_element(By.LINK_TEXT, "喷涂（机）").click()
    self.driver.find_element(By.LINK_TEXT, "喷涂（手）").click()
    element = self.driver.find_element(By.LINK_TEXT, "喷涂（手）")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "包装").click()
    element = self.driver.find_element(By.LINK_TEXT, "包装")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "生产日报").click()
    self.driver.find_element(By.LINK_TEXT, "退出").click()
    self.driver.find_element(By.ID, "userName").send_keys("卢鹏")
    self.driver.find_element(By.ID, "password").send_keys("123456")
  
if __name__ == '__main__':
    pytest.main()
